version: '3.8'

services:
  mysql_container:
    image: mysql:8.2.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: file_extension
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root -prootpassword || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
      - db_cnf:/etc/mysql/conf.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    networks:
      - app-network

  app_container:
    container_name: app_container
    image: jiin519/block-extension:2.0
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/file_extension
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db_data: {}
  db_log: {}
  db_cnf: {}

networks:
  app-network:
    driver: bridge
